"""
Load the parsed lift-programming catalog into ai_layer.lift_templates and
ai_layer.lift_template_exercises.

Source: skills/lift-programming/references/template_catalog.json
        (generated by skills/lift-programming/scripts/parse_templates.py)

Idempotent: each run does a TRUNCATE + reload. Safe to re-run after the
coach updates the spreadsheet — just regenerate the catalog then rerun this.

Run:
    python -m src.main load-templates
"""
from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any

from psycopg2.extras import execute_values

from src.db import backend_conn, exec_sql, query

CATALOG_PATH = (
    Path(__file__).resolve().parents[1]
    / "skills" / "lift-programming" / "references" / "template_catalog.json"
)

# Decode tables — same as in the skill's id_legend.md
_LEVEL = {
    "1": "Before Baseball Club (Beginner)",
    "2": "Baseball Club (Advanced)",
    "3": "High School (Beginner)",
    "4": "High School",
    "5": "College",
    "6": "Pro",
    "7": "Softball",
    "8": "Misc",
}
_FOCUS = {
    "1": "Strength",
    "2": "Power",
    "3": "Speed",
    "4": "In-Season",
    "5": "Hypertrophy",
}
_MOVEMENT = {
    "1": "Legs",
    "2": "Upper",
    "3": "Total Body",
    "4": "Sprint",
    "5": "Jump",
    "6": "Push",
    "7": "Pull",
    "8": "Core",
    "9": "Recovery",
}


def _decode_family(family_id: str | None) -> dict[str, Any]:
    """Decode the first 4 digits (family/numeric id) → level, focus, sprint days, variant."""
    out: dict[str, Any] = {
        "athlete_level": None, "focus": None,
        "sprint_days_per_week": None, "variant_identifier": None,
    }
    if not family_id or not family_id.isdigit():
        return out
    digits = list(family_id)
    if len(digits) >= 1: out["athlete_level"] = _LEVEL.get(digits[0])
    if len(digits) >= 2: out["focus"] = _FOCUS.get(digits[1])
    if len(digits) >= 3 and digits[2].isdigit():
        out["sprint_days_per_week"] = int(digits[2])
    if len(digits) >= 4: out["variant_identifier"] = digits[3]
    return out


def _decode_mesocycle_suffix(suffix: str | None) -> dict[str, Any]:
    """Decode the mesocycle_id portion (digits after the dash) → mesocycle # + movement bucket + lift position."""
    out: dict[str, Any] = {
        "mesocycle_number": None,
        "movement_bucket": None,
        "lift_position_in_day": None,
    }
    if not suffix:
        return out
    s = str(suffix).strip()
    if not s.isdigit():
        return out
    digits = list(s)
    if len(digits) >= 1 and digits[0].isdigit():
        out["mesocycle_number"] = int(digits[0])
    if len(digits) >= 2:
        out["movement_bucket"] = _MOVEMENT.get(digits[1])
    if len(digits) >= 3:
        out["lift_position_in_day"] = digits[2]
    return out


_SXR_PATTERN = re.compile(
    r"^\s*(?P<sets>\d+)\s*[xX×]\s*(?P<reps>\d+)\s*(?P<unit>s|sec|min)?\s*$"
)


def _parse_sets_reps(sxr: str | None) -> tuple[int | None, int | None]:
    """Best-effort parse of '3 x 5' / '3x10' / '1 x 60s' → (sets, reps). Time-based
    formats keep `sets` and put the duration in `reps` only if it's a pure number;
    otherwise reps is left as NULL and the raw string is preserved in sets_x_reps."""
    if not sxr:
        return None, None
    m = _SXR_PATTERN.match(str(sxr))
    if not m:
        return None, None
    try:
        sets = int(m.group("sets"))
    except (TypeError, ValueError):
        sets = None
    try:
        reps = int(m.group("reps"))
    except (TypeError, ValueError):
        reps = None
    return sets, reps


def _build_template_id(id_numeric: str | None, mesocycle_id: str | None,
                       raw_header: str | None) -> str:
    """Canonical template_id. Falls back to the raw header for named (non-numeric)
    templates so we still capture them."""
    if id_numeric and mesocycle_id:
        return f"{id_numeric}-{mesocycle_id}"
    if raw_header:
        return raw_header.strip()
    return f"unknown-{id_numeric or mesocycle_id or 'x'}"


def load_catalog(catalog_path: Path = CATALOG_PATH) -> dict[str, int]:
    """Wipe + reload ai_layer.lift_templates and lift_template_exercises from JSON."""
    if not catalog_path.exists():
        raise FileNotFoundError(
            f"Catalog not found at {catalog_path}. "
            f"Regenerate it via: python -m scripts.parse_templates "
            f"(in the skills/lift-programming/ directory)"
        )
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    index = catalog.get("index", {})
    blocks = catalog.get("blocks", [])

    templates_to_insert: list[tuple] = []
    exercises_to_insert: list[tuple] = []
    seen_template_ids: set[str] = set()

    for block_i, block in enumerate(blocks):
        for level_tag, level_data in (block.get("levels") or {}).items():
            header = (level_data or {}).get("header") or {}
            id_numeric = header.get("id_numeric")
            mesocycle_id = header.get("mesocycle_id")
            raw_header = header.get("raw")
            description = header.get("description")

            template_id = _build_template_id(id_numeric, mesocycle_id, raw_header)
            if template_id in seen_template_ids:
                # Skip duplicates — keep first occurrence as canonical
                continue
            seen_template_ids.add(template_id)

            family_decode = _decode_family(id_numeric)
            meso_decode = _decode_mesocycle_suffix(mesocycle_id)
            family_meta = (
                index.get(id_numeric, {}) if id_numeric else {}
            )

            templates_to_insert.append((
                template_id,
                id_numeric,
                raw_header,
                description,
                family_decode["athlete_level"],
                family_decode["focus"],
                family_decode["sprint_days_per_week"],
                family_decode["variant_identifier"],
                meso_decode["mesocycle_number"],
                meso_decode["movement_bucket"],
                meso_decode["lift_position_in_day"],
                family_meta.get("description"),
                json.dumps(family_meta.get("made_for_athletes") or []),
                family_meta.get("notes"),
                block_i,
            ))

            for ex_idx, ex in enumerate(level_data.get("exercises") or []):
                name = ex.get("exercise")
                sxr = ex.get("sets_x_reps")
                if not name:
                    continue
                parsed_sets, parsed_reps = _parse_sets_reps(sxr)
                exercises_to_insert.append((
                    template_id, ex_idx, name, sxr, parsed_sets, parsed_reps,
                ))

    # Wipe + reload using batched INSERTs (executemany is ~50x slower over network)
    t_start = time.time()
    print(f"[templates] parsed {len(templates_to_insert)} templates "
          f"and {len(exercises_to_insert)} exercises from catalog", flush=True)

    with backend_conn() as conn:
        print("[templates] truncating existing rows...", flush=True)
        exec_sql(conn, "TRUNCATE ai_layer.lift_templates CASCADE")

        with conn.cursor() as cur:
            print("[templates] inserting templates...", flush=True)
            t0 = time.time()
            execute_values(cur, """
                INSERT INTO ai_layer.lift_templates
                  (template_id, family_id, raw_header, description,
                   athlete_level, focus, sprint_days_per_week, variant_identifier,
                   mesocycle_number, movement_bucket, lift_position_in_day,
                   family_description, made_for_athletes, family_notes,
                   source_block_index)
                VALUES %s
            """,
            templates_to_insert,
            template="(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s::jsonb, %s, %s)",
            page_size=200)
            print(f"[templates]   {len(templates_to_insert)} templates in "
                  f"{int((time.time()-t0)*1000)} ms", flush=True)

            print("[templates] inserting exercises...", flush=True)
            t0 = time.time()
            execute_values(cur, """
                INSERT INTO ai_layer.lift_template_exercises
                  (template_id, exercise_order, exercise_name, sets_x_reps,
                   parsed_sets, parsed_reps)
                VALUES %s
            """,
            exercises_to_insert,
            page_size=500)
            print(f"[templates]   {len(exercises_to_insert)} exercises in "
                  f"{int((time.time()-t0)*1000)} ms", flush=True)

    print(f"[templates] total load time: {int((time.time()-t_start)*1000)} ms", flush=True)

    return {
        "n_templates": len(templates_to_insert),
        "n_exercises": len(exercises_to_insert),
        "n_families": len({t[1] for t in templates_to_insert if t[1]}),
    }


def summary() -> None:
    """Print quick stats on what's loaded."""
    with backend_conn() as conn:
        rows = query(conn, """
            SELECT COUNT(*) AS n_templates,
                   COUNT(DISTINCT family_id) AS n_families,
                   COUNT(DISTINCT athlete_level) AS n_levels,
                   COUNT(DISTINCT movement_bucket) AS n_movement_buckets
            FROM ai_layer.lift_templates
        """)
        print(f"  templates:       {rows[0]['n_templates']}")
        print(f"  families:        {rows[0]['n_families']}")
        print(f"  athlete levels:  {rows[0]['n_levels']}")
        print(f"  movement buckets:{rows[0]['n_movement_buckets']}")

        ex = query(conn, """
            SELECT COUNT(*) AS n FROM ai_layer.lift_template_exercises
        """)
        print(f"  exercises:       {ex[0]['n']}")

        by_level = query(conn, """
            SELECT COALESCE(athlete_level, '(named/unknown)') AS lvl,
                   COUNT(*) AS templates
            FROM ai_layer.lift_templates
            GROUP BY lvl
            ORDER BY templates DESC
        """)
        print("\n  templates by athlete level:")
        for r in by_level:
            print(f"    {r['lvl']:<35} {r['templates']:>4}")


if __name__ == "__main__":
    result = load_catalog()
    print(f"[templates] loaded {result['n_templates']} templates, "
          f"{result['n_exercises']} exercises across {result['n_families']} families")
    summary()
